[package]
name = "rust-iot"
version = "0.1.0"
authors = ["zed.zy <zed.zy@antgroup.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
rustun = "0.3"
fibers_global = "0.1"
